### ISSUE TITLE
bug with new ROOT version.

### ISSUE THREAD

**Issue by cxwx** [akira-okumura/PyTeVCat#4]
Anyway, thanks for the help of this repo to got list from website.
This saved me a lot of time.

just an version bug.
ROOT version 6.22.0
TGMainFrame' has private copy constructor which should not be used in python code at least now.

error message when `import tevcat`
```
input_line_40:9:43: error: base class '::TGMainFrame' has private copy constructor
  Dispatcher1(const Dispatcher1& other) : TGMainFrame(other), m_self(other.m_self, this) {}
                                          ^
/usr/local/Cellar/root/6.22.00_1/include/root/TGFrame.h:487:4: note: declared private here
   TGMainFrame(const TGMainFrame&);             // not implemented
   ^
/Users/chenxu/software/python/envPy38/lib/python3.8/site-packages/tevcat/tevcat_all.py:459: RuntimeWarning: no python-side overrides supported
  class Viewer(ROOT.TGMainFrame):
```

**Comment by akira-okumura** [comment]
It’s a ROOT 6.22/00 bug that is already known to the dev team, but I could not find the issue ticket on ROOT JIRA. I think I cannot do anything easily from my side at the moment, and the next ROOT patch release is needed.

**Comment by akira-okumura** [comment]
- https://sft.its.cern.ch/jira/browse/ROOT-10826
- https://root-forum.cern.ch/t/pyroot-experimental-not-working-in-6-20-06/40059/13

**Comment by cxwx** [comment]
fixed by root
